execute_process(COMMAND "${CLI}" -o "${WORK_DIR}/subtitle-style-order.iso" --subtitle-file-style size=32 missing.mkv RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "requires --subtitle-file first")
  message(FATAL_ERROR "subtitle-file style ordering regression: ${err}")
endif()
execute_process(COMMAND "${CLI}" -o "${WORK_DIR}/subtitle-style-invalid.iso" --subtitle-stream-style 1 dvd-halign=diagonal missing.mkv RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "dvd-halign must be default, left, center, or right")
  message(FATAL_ERROR "subtitle style validation regression: ${err}")
endif()
execute_process(COMMAND "${CLI}" -o "${WORK_DIR}/subtitle-style-accepted.iso" --subtitle-stream-style 1 font=DejaVuSans --subtitle-stream-style 1 size=30 --subtitle-stream-style 1 "color=#ffff00" --subtitle-stream-style 1 border=2.5 --subtitle-file missing.srt --subtitle-file-style dvd-shadow-x=2 --subtitle-file-style dvd-force=yes missing.mkv RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "missing title source")
  message(FATAL_ERROR "subtitle style CLI options were not accepted before project validation: ${err}")
endif()
