file(READ "${SOURCE_DIR}/src/author.cpp" AUTHOR_SRC)
file(READ "${SOURCE_DIR}/third_party/tsmuxer/tsMuxer/tsMuxer.cpp" MUX_SRC)
file(READ "${SOURCE_DIR}/third_party/tsmuxer/tsMuxer/metaDemuxer.cpp" META_SRC)
file(READ "${SOURCE_DIR}/third_party/tsmuxer/tsMuxer/tsPacket.cpp" PACKET_SRC)
foreach(needle "S_HDMV/IGS" "menu.igs" "--start-time=")
  string(FIND "${AUTHOR_SRC}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "authoring source missing ${needle}")
  endif()
endforeach()
foreach(needle "0x1400" "StreamType::SUB_IGS")
  string(FIND "${MUX_SRC}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "tsMuxer source missing ${needle}")
  endif()
endforeach()
string(FIND "${META_SRC}" "setInteractiveGraphics(true)" pos)
if(pos EQUAL -1)
  message(FATAL_ERROR "IG graphics-reader mode is not enabled")
endif()
foreach(needle "number_of_IG_stream_entries++" "writer.putBits(8, number_of_IG_stream_entries)" "StreamType::SUB_PGS || stream_coding_type == StreamType::SUB_IGS")
  string(FIND "${PACKET_SRC}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "MPLS/CLPI IGS source missing ${needle}")
  endif()
endforeach()
foreach(forbidden "menu-placeholder.sup" "replace_pgs_placeholder_with_igs" "patch_bdmv_graphics_descriptors")
  string(FIND "${AUTHOR_SRC}" "${forbidden}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "obsolete PGS patch path still present: ${forbidden}")
  endif()
endforeach()

string(FIND "${AUTHOR_SRC}" "hdmv::kBluRayMuxStartPts90k / 2U" pos)
if(pos EQUAL -1)
  message(FATAL_ERROR "MUXOPT start time is not derived from the shared 90 kHz Blu-ray timing constant")
endif()
