if(NOT DEFINED CLI OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "CLI/WORK_DIR not supplied")
endif()
set(dummy "${WORK_DIR}/menuless-cli-dummy.mp4")
set(image "${WORK_DIR}/menuless-cli-output.iso")
file(WRITE "${dummy}" "")
execute_process(COMMAND "${CLI}" -o "${image}" --no-menu "${dummy}"
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
set(text "${out}${err}")
if(rc EQUAL 0)
  message(FATAL_ERROR "empty dummy unexpectedly authored successfully")
endif()
foreach(bad "unknown option: --no-menu" "project has no top menu" "needs at least one button")
  string(FIND "${text}" "${bad}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "menuless project rejected before media probing: ${text}")
  endif()
endforeach()
string(FIND "${text}" "ffprobe" probe_pos)
if(probe_pos EQUAL -1)
  message(FATAL_ERROR "menuless project did not survive validation to media probing: ${text}")
endif()
file(REMOVE "${dummy}" "${image}")
message(STATUS "menuless CLI validation checks ok")
