execute_process(COMMAND "${CLI}" -o "${WORK_DIR}/downmix-invalid.iso" --audio-stream-channels 1 9.1 missing.mkv RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "must be source, mono, stereo, quad, 5.1, or 7.1")
  message(FATAL_ERROR "invalid channel-layout CLI regression: ${err}")
endif()
execute_process(COMMAND "${CLI}" -o "${WORK_DIR}/subtitle-language-invalid.iso" --subtitle-file-language eng missing.mkv RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "requires --subtitle-file first")
  message(FATAL_ERROR "subtitle-file language ordering regression: ${err}")
endif()
execute_process(COMMAND "${CLI}" -o "${WORK_DIR}/downmix-accepted.iso" --audio-stream-channels 1 stereo --subtitle-file missing.srt --subtitle-file-language eng missing.mkv RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(rc EQUAL 0 OR NOT err MATCHES "missing title source")
  message(FATAL_ERROR "new CLI options were not accepted before project validation: ${err}")
endif()
