if(NOT DEFINED CLI)
  message(FATAL_ERROR "CLI path not supplied")
endif()
function(expect_rejected name expected)
  execute_process(COMMAND "${CLI}" ${ARGN} RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(rc EQUAL 0)
    message(FATAL_ERROR "${name}: invalid target/codec selection unexpectedly succeeded")
  endif()
  set(text "${out}${err}")
  string(FIND "${text}" "${expected}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${name}: expected '${expected}', got: ${text}")
  endif()
endfunction()

# Ultra HD Blu-ray v3 permits AVC/H.264 only for 1920x1080p23.976/24 bonus-feature style video.
execute_process(COMMAND "${CLI}" --target uhd --video-codec x264 --title-resolution 1920x1080 --title-frame-rate 24p dummy.mp4 RESULT_VARIABLE uhd_avc_ok_rc OUTPUT_VARIABLE uhd_avc_ok_out ERROR_VARIABLE uhd_avc_ok_err)
set(uhd_avc_ok_text "${uhd_avc_ok_out}${uhd_avc_ok_err}")
string(FIND "${uhd_avc_ok_text}" "missing title source" uhd_avc_ok_pos)
if(uhd_avc_ok_pos EQUAL -1)
  message(FATAL_ERROR "valid UHD AVC 1080p24 profile did not pass option/mode validation: ${uhd_avc_ok_text}")
endif()
expect_rejected("UHD AVC 2160p" "resolution/aspect/frame-rate selection is not legal" --target uhd --video-codec x264 --title-resolution 3840x2160 --title-frame-rate 24p dummy.mp4)
expect_rejected("UHD AVC 1080p25" "resolution/aspect/frame-rate selection is not legal" --target uhd --video-codec x264 --title-resolution 1920x1080 --title-frame-rate 25p dummy.mp4)
expect_rejected("UHD AVC 41 Mb/s" "between 1000 and 40000 kb/s" --target uhd --video-codec x264 --video-bitrate 41000 dummy.mp4)
execute_process(COMMAND "${CLI}" --target bluray --video-codec x264 --title-resolution 1920x1080 --title-frame-rate 25p dummy.mp4 RESULT_VARIABLE bd_fake_ok_rc OUTPUT_VARIABLE bd_fake_ok_out ERROR_VARIABLE bd_fake_ok_err)
set(bd_fake_ok_text "${bd_fake_ok_out}${bd_fake_ok_err}")
string(FIND "${bd_fake_ok_text}" "missing title source" bd_fake_ok_pos)
if(bd_fake_ok_pos EQUAL -1)
  message(FATAL_ERROR "valid Blu-ray AVC 1080p25 fake-interlaced profile did not pass option/mode validation: ${bd_fake_ok_text}")
endif()
expect_rejected("standard Blu-ray MPEG-2 1080p25" "resolution/aspect/frame-rate selection is not legal" --target bluray --video-codec mpeg2 --title-resolution 1920x1080 --title-frame-rate 25p dummy.mp4)
expect_rejected("standard Blu-ray HEVC" "allows only x264 or mpeg2" --target bluray --video-codec hevc dummy.mp4)
expect_rejected("DVD AVC" "allows only mpeg2" --target dvd --video-codec x264 dummy.mp4)
expect_rejected("DVD DTS" "allows only ac3 or lpcm" --target dvd --audio-codec dca dummy.mp4)
expect_rejected("DVD TrueHD" "allows only ac3 or lpcm" --target dvd --audio-codec truehd dummy.mp4)
expect_rejected("DVD AC-3 640" "448 kb/s AC-3 limit" --target dvd --audio-bitrate 640 dummy.mp4)
expect_rejected("DVD video 12 Mb/s" "between 1000 and 9800 kb/s" --target dvd --video-bitrate 12000 dummy.mp4)

execute_process(COMMAND "${CLI}" --target dvd --video-codec mpeg2 --video-bitrate 9800 --audio-codec ac3 --audio-bitrate 448 dummy.mp4 RESULT_VARIABLE ok_rc OUTPUT_VARIABLE ok_out ERROR_VARIABLE ok_err)
set(ok_text "${ok_out}${ok_err}")
string(FIND "${ok_text}" "missing title source" ok_pos)
if(ok_pos EQUAL -1)
  message(FATAL_ERROR "valid DVD profile did not pass option validation: ${ok_text}")
endif()
message(STATUS "target codec CLI rejection/acceptance checks ok")
