if(NOT DEFINED MKISOFS OR NOT DEFINED FIXTURE_WRITER OR NOT DEFINED WORK_DIR)
  message(FATAL_ERROR "MKISOFS, FIXTURE_WRITER and WORK_DIR are required")
endif()
set(root "${WORK_DIR}/mkisofs-runtime-test")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}/dvd/VIDEO_TS" "${root}/dvd/AUDIO_TS")
execute_process(COMMAND "${FIXTURE_WRITER}" "${root}/dvd/VIDEO_TS/VIDEO_TS.IFO" RESULT_VARIABLE frc ERROR_VARIABLE ferr)
if(NOT frc EQUAL 0)
  message(FATAL_ERROR "could not generate minimal DVD-Video fixture: ${ferr}")
endif()
file(COPY_FILE "${root}/dvd/VIDEO_TS/VIDEO_TS.IFO" "${root}/dvd/VIDEO_TS/VIDEO_TS.BUP")
execute_process(COMMAND "${MKISOFS}" -version RESULT_VARIABLE vrc OUTPUT_VARIABLE vout ERROR_VARIABLE verr)
if(NOT vrc EQUAL 0 OR NOT "${vout}${verr}" MATCHES "mkisofs 3\\.02a09")
  message(FATAL_ERROR "vendored mkisofs version check failed: ${vout}${verr}")
endif()
execute_process(COMMAND "${MKISOFS}" RESULT_VARIABLE nrc OUTPUT_VARIABLE nout ERROR_VARIABLE nerr)
if(nrc EQUAL 0)
  message(FATAL_ERROR "vendored mkisofs without a pathspec unexpectedly succeeded")
endif()
# Native Windows reports argv[0] as mkisofs.exe while Unix reports mkisofs.
# Normalize line endings, then accept either native basename without weakening the
# required diagnostic text.
string(REPLACE "\r\n" "\n" nerr_normalized "${nerr}")
string(REPLACE "\r" "\n" nerr_normalized "${nerr_normalized}")
if(NOT "${nerr_normalized}" MATCHES "mkisofs(\\.exe)?:[ \n]*Missing pathspec\\.")
  message(FATAL_ERROR "vendored mkisofs missing-pathspec diagnostic is malformed: ${nerr}")
endif()
foreach(forbidden "Unknown error -1" "Unknown error")
  string(FIND "${nerr}" "${forbidden}" badpos)
  if(NOT badpos EQUAL -1)
    message(FATAL_ERROR "vendored mkisofs missing-pathspec diagnostic contains stale error text '${forbidden}': ${nerr}")
  endif()
endforeach()
execute_process(
  COMMAND "${MKISOFS}" -dvd-video -V BDMVTEST -o "${root}/dvd.iso" "${root}/dvd"
  RESULT_VARIABLE rc OUTPUT_VARIABLE out ERROR_VARIABLE err)
if(NOT rc EQUAL 0)
  message(FATAL_ERROR "vendored mkisofs -dvd-video smoke test failed (${rc}): ${out}${err}")
endif()
if(NOT EXISTS "${root}/dvd.iso")
  message(FATAL_ERROR "vendored mkisofs did not create DVD image")
endif()
file(SIZE "${root}/dvd.iso" iso_size)
if(iso_size LESS 600000)
  message(FATAL_ERROR "vendored mkisofs DVD image is unexpectedly small: ${iso_size}")
endif()
# ISO9660 primary volume descriptor at logical block 16: type 1 + CD001.
file(READ "${root}/dvd.iso" pvd OFFSET 32768 LIMIT 6 HEX)
string(TOLOWER "${pvd}" pvd)
if(NOT pvd STREQUAL "014344303031")
  message(FATAL_ERROR "DVD image lacks ISO9660 PVD signature at sector 16: ${pvd}")
endif()
# DVD-Video mode must also emit the UDF volume recognition sequence.
file(READ "${root}/dvd.iso" head OFFSET 32768 LIMIT 65536 HEX)
string(TOLOWER "${head}" head)
string(FIND "${head}" "4e53523032" nsr02)
string(FIND "${head}" "4e53523033" nsr03)
if(nsr02 EQUAL -1 AND nsr03 EQUAL -1)
  message(FATAL_ERROR "DVD image lacks UDF NSR02/NSR03 volume recognition descriptor")
endif()
file(REMOVE_RECURSE "${root}")
message(STATUS "vendored mkisofs DVD-Video runtime smoke test ok")
