function(run_case name target rate expect_frame_error)
  execute_process(
    COMMAND "${CLI}" --target "${target}" --frame-rate "${rate}" ${ARGN} -o "${WORK_DIR}/${name}.iso" "${WORK_DIR}/${name}-missing-input.mkv"
    RESULT_VARIABLE rv OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(rv EQUAL 0)
    message(FATAL_ERROR "${name}: command unexpectedly succeeded")
  endif()
  set(text "${out}${err}")
  string(FIND "${text}" "frame-rate override" pos)
  if(expect_frame_error)
    if(pos EQUAL -1)
      message(FATAL_ERROR "${name}: expected frame-rate rejection, got: ${text}")
    endif()
  else()
    if(NOT pos EQUAL -1)
      message(FATAL_ERROR "${name}: legal frame-rate override was rejected: ${text}")
    endif()
    string(FIND "${text}" "missing title source" missing)
    if(missing EQUAL -1)
      message(FATAL_ERROR "${name}: expected validation to advance to missing source, got: ${text}")
    endif()
  endif()
endfunction()
run_case(uhd_2997 uhd 29.97p TRUE)
run_case(uhd_60 uhd 60p FALSE)
run_case(bd_25p bluray 25p FALSE)
run_case(bd_2997p bluray 29.97p FALSE)
run_case(bd_50i bluray 50i FALSE)
run_case(bd_60p bluray 60p TRUE)
run_case(dvd_film dvd film-dvd FALSE)
run_case(dvd_ntsc dvd ntsc-dvd FALSE)
run_case(dvd_pal dvd pal-dvd FALSE --menu-resolution 720x576)
run_case(dvd_60p dvd 60p TRUE)
message(STATUS "target-specific frame-rate CLI validation ok")

function(run_title_case name target rate expect_frame_error)
  execute_process(
    COMMAND "${CLI}" --target "${target}" --title-frame-rate "${rate}" ${ARGN} -o "${WORK_DIR}/${name}.iso" "${WORK_DIR}/${name}-missing-input.mkv"
    RESULT_VARIABLE rv OUTPUT_VARIABLE out ERROR_VARIABLE err)
  if(rv EQUAL 0)
    message(FATAL_ERROR "${name}: command unexpectedly succeeded")
  endif()
  set(text "${out}${err}")
  string(FIND "${text}" "title frame-rate override" pos)
  if(expect_frame_error)
    if(pos EQUAL -1)
      message(FATAL_ERROR "${name}: expected per-title frame-rate rejection, got: ${text}")
    endif()
  else()
    if(NOT pos EQUAL -1)
      message(FATAL_ERROR "${name}: legal per-title frame-rate override was rejected: ${text}")
    endif()
    string(FIND "${text}" "missing title source" missing)
    if(missing EQUAL -1)
      message(FATAL_ERROR "${name}: expected validation to advance to missing source, got: ${text}")
    endif()
  endif()
endfunction()
run_title_case(title_bd_24 bluray 24p FALSE)
run_title_case(title_bd_25p bluray 25p FALSE)
run_title_case(title_bd_2997p bluray 29.97p FALSE)
run_title_case(title_bd_60p bluray 60p TRUE)
run_title_case(title_uhd_50p uhd 50p FALSE)
run_title_case(title_dvd_film dvd film-dvd FALSE)
run_title_case(title_dvd_pal dvd pal-dvd FALSE --menu-resolution 720x576)

execute_process(
  COMMAND "${CLI}" --target dvd --title-frame-rate film-dvd "${WORK_DIR}/mixed-film-missing.mkv" --title-frame-rate ntsc-dvd "${WORK_DIR}/mixed-ntsc-missing.mkv"
  RESULT_VARIABLE mixed_ok_rv OUTPUT_VARIABLE mixed_ok_out ERROR_VARIABLE mixed_ok_err)
set(mixed_ok_text "${mixed_ok_out}${mixed_ok_err}")
string(FIND "${mixed_ok_text}" "DVD-Video cannot mix PAL titles" mixed_ok_bad)
if(NOT mixed_ok_bad EQUAL -1)
  message(FATAL_ERROR "DVD Film+NTSC combination was incorrectly rejected: ${mixed_ok_text}")
endif()

execute_process(
  COMMAND "${CLI}" --target dvd --title-frame-rate film-dvd "${WORK_DIR}/mixed-film-pal-missing.mkv" --title-frame-rate pal-dvd "${WORK_DIR}/mixed-pal-missing.mkv"
  RESULT_VARIABLE mixed_bad_rv OUTPUT_VARIABLE mixed_bad_out ERROR_VARIABLE mixed_bad_err)
set(mixed_bad_text "${mixed_bad_out}${mixed_bad_err}")
string(FIND "${mixed_bad_text}" "DVD-Video cannot mix PAL titles/resolutions with Film/NTSC titles/resolutions on the same disc" mixed_bad_pos)
if(mixed_bad_pos EQUAL -1)
  message(FATAL_ERROR "DVD Film+PAL incompatibility was not rejected: ${mixed_bad_text}")
endif()
